# Les vecteurs et matrices 

Si Matlab est l'acronyme de *Matrix Laboratory*, ce n'est pas pour rien (et ce n'est pas un hommage aux films des Wachowski non plus). En effet, il permet de manipuler facilement des tableaux à une ou plusieurs dimensions (ce que nous connaissons sous le nom de vecteurs ou matrices, respectivement). Nous verrons dans ce chapitre comment les définir, accéder à leurs éléments et réaliser les opérations les plus fréquentes avec eux. Nous essayerons d'expliquer les concepts de façon la plus claire possible, adaptée à des débutants dans ce langage, mais pour toute question ou remarque sur les explications de ce chapitre, n'hésitez pas à contacter son auteur Carlos Sosa Marrero (carlos.sosa@univ-rennes1.fr).

## Les vecteurs
### Définition de vecteurs
Il existe plusieurs manières de définir des vecteurs en Matlab. 
Une première façon consiste à utiliser des crochets `[.]` et lister les valeurs que nous voulons inclure dans notre vecteur séparées par une virgule et/ou un espace. Nous vous montrons un exemple de vecteur ligne de trois éléments.

In [338]:
v = [7, -5, 3]

v =

   7  -5   3



Nous pouvons également construire des vecteurs colonne. Pour cela, nous séparons les différentes lignes avec un point-virgule `;` et/ou un retour chariot. 

In [339]:
w = [1; 6; -4]

w =

   1
   6
  -4



Nous pouvons aussi définir des vecteurs ligne à partir de suites arithmétiques. Nous construissons ces suites en tapant `n:p:m`, où `n` est la limite à gauche; `p`, le pas et `m`, la limite à droite. Ainsi, pour construire, par exemple, un vecteur dont les éléments correspondent aux nombres pairs appartenant à [4, 18] en ordre croissant, nous devons taper

In [340]:
v = 4:2:18

v =

    4    6    8   10   12   14   16   18



En indiquant une valeur de `n` plus grande que celle de `m` et un pas négatif, nous pouvons construire une suite décroissante pour définir notre vecteur.

In [341]:
v = 18:-2:4

v =

   18   16   14   12   10    8    6    4



Si nous n'indiquons pas la valeur `p` de la suite, Matlab considère un pas unitaire, comme nous pouvons remarquer dans l'exemple suivant.

In [342]:
w = 3:12

w =

    3    4    5    6    7    8    9   10   11   12



Il est également possible de définir un vecteur en utilisant la fonction Matlab `linspace(a, b, n)`. Elle renvoie un vecteur ligne composé de  `n` éléments régulièrement espacés de `a`à `b`. Nous vous montrons un exemple d'utilisation de cette fonction.

In [343]:
v = linspace(0, 5, 11)

v =

 Columns 1 through 8:

   0.00000   0.50000   1.00000   1.50000   2.00000   2.50000   3.00000   3.50000

 Columns 9 through 11:

   4.00000   4.50000   5.00000



#### Longueur d'un vecteur
La fonction `length(v)` permet d'obtenir la longueur du vecteur `v`.

In [344]:
v = [7, -5, 3];
longueur = length(v)

longueur =  3


### Accès aux éléments d'un vecteur
L'accès aux éléments d'un vecteur se fait à l'aide de parenthèses `(.)`. Par exemple, pour accéder au deuxième élément du vecteur `u`, il suffit de taper

In [345]:
u = [4, -6, 1, 9, -8];
u2 = u(2)

u2 = -6


Fréquemment, il est nécessaire d'accéder à plusieurs éléments d'un vecteur. Pour cela, nous indiquons les indices du premier et du dernier élément souhaités séparés par deux points `:`. Par exemple, l'accès aux trois premiers éléments du vecteur `u` se fait en tapant 

In [346]:
u = [4, -6, 1, 9, -8];
u1a3 = u(1:3)

u1a3 =

   4  -6   1



### Opérations avec les vecteurs
Matlab permet d'effectuer un grand nombre d'opérations avec les vecteurs. Commençons par les plus basiques.
#### Opérations arithmétiques basiques
Soient deux vecteurs de la même longueur, nous pouvons calculer leur somme et leur différence comme nous vous montrons dans l'exemple suivant.

In [347]:
u = [4, -6, 1, 9, -8];
v = [-3, 7, 10, 4, -5];
somme = u + v
diff = u - v

somme =

    1    1   11   13  -13

diff =

    7  -13   -9    5   -3



La multiplication ou la division d'un vecteur `u` par un scalaire `k` se réalise aussi de façon assez intuitive. Comme vous pouvez vous en douter, il suffit de taper 

In [348]:
u = [4, -6, 1, 9, -8];
k = 2;
prodk = k * u
divk = u / k

prodk =

    8  -12    2   18  -16

divk =

   2.00000  -3.00000   0.50000   4.50000  -4.00000



#### Produit scalaire
Nous pouvons calculer le produit scalaire de deux vecteurs `u` et `v` à l'aide de la fonction Matlab `dot(u, v)`. Regardons un exemple.

In [349]:
u = [4, -6, 1, 9, -8];
v = [-3, 7, 10, 4, -5];
prodScal = dot(u, v)

prodScal =  32


#### Opérations terme à terme
Soient toujours `u` et `v` deux vecteurs de la même taille, nous pouvons nous intéresser à un vecteur `w` dont l'i-ème élément correspond au produit des i-èmes éléments de `u` et `v`. C'est ce que nous appelons le produit terme à terme et nous pouvons le calculer en ajoutant un point `.` devant l'opérateur produit classique. Nous vous en montrons un exemple.  

In [350]:
u = [4, -6, 1, 9, -8];
v = [-3, 7, 10, 4, -5];
prodTaT = u .* v

prodTaT =

  -12  -42   10   36   40



De façon analogique, nous pouvons calculer un vecteur résultant de la division terme à terme de `u` entre `v` comme  nous vous montrons dans l'exemple suivant.

In [351]:
u = [4, -6, 1, 9, -8];
v = [-3, 7, 10, 4, -5];
divTaT = u ./ v

divTaT =

  -1.33333  -0.85714   0.10000   2.25000   1.60000



Et comment faudrait-il faire pour obtenir un vecteur `u2` dont l'i-ème élément correspond au carré de l'i-ème élément de `u` ?. Nous sommes sûrs que, arrivés à ce point, vous comprenez que cette opération se réalise de la manière suivante. 

In [352]:
u = [4, -6, 1, 9, -8];
u2 = u .^2

u2 =

   16   36    1   81   64



#### Transposé d'un vecteur
Le transposé d'un vecteur (passage de vecteur ligne à colonne et vice versa) se réalise à l'aide de l'opérateur `'`. Nous vous en montrons un exemple.

In [353]:
u = [4, -6, 1, 9, -8];
ut = u'

ut =

   4
  -6
   1
   9
  -8



#### Concaténation de vecteurs
La concaténation de deux vecteurs en Matlab se fait aussi de façon assez simple. Soient deux vecteurs ligne `u` et `v`, nous pouvons construire un troisième vecteur `w` en concaténant `u` et `v`comme nous vous montrons dans l'exemple suivant.

In [354]:
u = [4, -6, 1, 9, -8];
v = [-3, 7, 10, 4, -5];
w = [u, v]

w =

    4   -6    1    9   -8   -3    7   10    4   -5



En effet, nous pouvons voir cette opération comme si nous construisions le vecteur `w` en listant ses deux éléments (`u` et `v`) entre crochets. Comme les deux sont dans la même ligne, nous les séparons, bien entendu, avec une virgule. En appliquant ce même raisonnement, vous pouvez déduire que la concaténation de deux vecteurs colonne se réalise de la façon suivante.

In [355]:
u = [4; -6; 1; 9; -8];
v = [-3; 7; 10; 4; -5];
w = [u; v]

w =

    4
   -6
    1
    9
   -8
   -3
    7
   10
    4
   -5



Nous avons fréquemment besoin d'ajouter un dernier élément `a` à un vecteur déjà créé `u`. Nous pouvons voir cette opération comme l'affectation à `u` de la concaténation entre sa valeur précédente et `a`. C'est-à-dire,

In [356]:
u = [4, -6, 1, 9, -8];
a = 2;
u = [u, a]

u =

   4  -6   1   9  -8   2



## Les matrices
### Définition de matrices
Maintenant que vous comprenez comment définir des vecteurs ligne ou colonne, la façon de déclarer une matrice en Matlab ne devrait pas vous poser trop de problèmes. Vous savez que les éléments d'un vecteur ligne sont séparés par une virgule et/ou un espace et que nous indiquons avec un point-virgule et/ou un retour chariot les transitions entre les différentes lignes d'un vecteur colonne. Et bien, avec ces deux règles en tête, nous sommes certains qu'il vous semble cohérent qu'une matrice  3 x 2 `A` soit définie de la manière suivante

In [357]:
A = [3, 6;
    7, -4;
    -1, 5]

A =

   3   6
   7  -4
  -1   5



En fait, comme vous l'avez peut-être déjà remarqué, Matlab considère les vecteurs comme un cas particulier d'une matrice avec une seule ligne ou colonne. 

#### Quelques fonctions utiles
Définir de petites matrices avec des crochets en listant tous leurs éléments c'est pratique, mais cette tache devient fatigante lorsque nous augmentons la taille de notre problème. Pensons, par exemple, à définir une matrice 100 x 200 dont tous les éléments sont égaux à zéro. Appuyer 20 000 fois sur la touche 0 du clavier semble une tâche assez répétitive. Heureusement, nous ne sommes pas les premiers à être confrontés à ce problème et Matlab en a déjà prévu une solution. Il s'agit de la fonction `zeros(m, n)`, qui définit une matrice de zéros de `m` lignes et `n` colonnes. Nous vous montrons deux exemples de l'utilisation de cette fonction. Amusez-vous à enlever le point-virgule du deuxième pour voir quelques zéros apparaître sur votre écran.

In [358]:
A = zeros(2, 3)
B = zeros(100, 200);

A =

   0   0   0
   0   0   0



Comme vous pouvez le déduire à partir du titre de la section, `zeros(m, n)` n'est pas la seule fonction que nous allons vous présenter dans ces lignes. Comment créeriez-vous une matrice de taille `m` x `n` dont tous les éléments sont égaux à l'unité ? Si vous avez bien compris le fonctionnement de `zeros(m, n)` et vous avez quelques connaissances basiques de la langue anglaise, vous devriez être capables de déduire que cela se fait à l'aide de la fonction `ones(m, n)` de la manière suivante. 

In [359]:
A = ones(2, 3)
B = ones(100, 200);

A =

   1   1   1
   1   1   1



Nous sommes sûrs que vous appréciez l'utilité de pouvoir créer d'énormes matrices en une seule ligne. Cependant, nous vous accordons que c'est un peu dommage de ne pouvoir créer que des matrices contenant des 0 ou des 1.  Comment définiriez-vous une matrice avec tous ses éléments égaux à, par exemple, 2 ? Et bien, non, la fonction ~~`twos(m, n)`~~ n'existe pas. Mais, ce n'est pas grave. Vous souvenez-vous de la façon dont nous avons multiplié un vecteur par une constante ? Et nous avons aussi dit que Matlab considère les vecteurs comme une matrice d'une seule ligne ou colonne, n'est-ce pas ? Nous vous proposons donc de créer une matrice avec tous ses éléments égaux à 2 de la façon suivante.

In [360]:
A = 2 * ones(2, 3)
B = 2 * ones(100, 200);

A =

   2   2   2
   2   2   2

